site_name: Resonant Reality
repo_url: https://github.com/TerralanMira/Resonant-reality
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
    scheme: slate
    primary: indigo
    accent: teal

nav:
  - Home: index.md
  - Field:
      - Earth Layer:
          - Overview: field/earth.md
          - Data: field/earth/data.md
      - Human Layer: field/human.md
      - Civic Layer:
          - Overview: civic/index.md
          - Conductor: civic/conductor.md
          - Plazas: civic/plazas.md
          - Rituals: civic/rituals.md
          - Hearths: civic/hearths.md
          - Governance: civic/governance.md
          - Education: civic/education.md
          - Economy: civic/economy.md
      - Cosmos Layer: cosmos/index.md
      - Bridge: bridge.md
  - Sims:
      - Overview: sims/index.md
      - Spiral Resonance: sims/spiral.md
      - Kuramoto Sync: sims/kuramoto.md
      - LC Grid Modes: sims/lc_grid.md
      - Schumann Coupling: sims/schumann.md
      - Resonant Currency: sims/resonant_currency.md
      - Atlas Model: sims/atlas.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
