site_name: Resonant Reality
site_description: "From myth to math to visible coherence — a Theory of Everything in fractal form."
site_url: https://terralanmira.github.io/Resonant-reality/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Simulations:
      - Overview: sims/index.md
      - Quickstart: sims/quickstart.md
      - Spiral Resonance: sims/spiral_resonance.md
      - Kuramoto Sync: sims/kuramoto.md
      - LC Grid Modes: sims/lc_grid.md
      - Schumann Coupling: sims/schumann.md
    - Overview: sims/index.md
    - Deepening: sims/deepening.md
    - Meta-Resonance: sims/meta.md
  - Earth Grid:
      - Data: earth/data.md
      - Resonance Map: earth/map.md
  - Cosmos:
      - Layers: cosmos/layers.md
      - Coupling: cosmos/coupling.md
  - City:
      - Garden: city/garden.md
      - Wild: city/wild.md
      - Civic Plaza: city/civic_plaza.md
      - Conductor: city/conductor.md
  - Frameworks:
      - Atlas Model: frameworks/atlas_model.md
      - Resonant Frameworks: frameworks/resonant_frameworks.md
  - Field:
      - Awareness: field/awareness.md
      - Coherence: field/coherence.md
      - Applications: field/applications.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
