site_name: Resonant Reality
site_description: A living atlas of resonance — from human breath to galactic spirals.
site_author: Terralan Mira
repo_url: https://github.com/TerralanMira/Resonant-reality

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    primary: indigo
    accent: amber

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - md_in_html

nav:
  - Home: index.md
  - Theory of Resonance: docs/theory.md

  - Simulations:
      - Overview: docs/sims/index.md
      - Quickstart: docs/sims/quickstart.md
      - Spiral Resonance: docs/sims/spiral_resonance.md
      - Kuramoto Sync: docs/sims/kuramoto.md
      - LC Grid Modes: docs/sims/lc_grid.md
      - Schumann Coupling: docs/sims/schumann.md
      - Resonant Currency: docs/sims/resonant_currency.md
      - Governance Sync: docs/sims/governance_sync.md
      - Civic Coherence Grid: docs/sims/civic_coherence_grid.md
      - Meta-Resonance: docs/sims/meta_resonance.md
      - Reciprocity Network: docs/sims/reciprocity_network.md
      # NEW cosmic sims
      - Planetary Orbital Resonance: docs/sims/planetary_orbital_resonance.md
      - Solar ↔ HRV Correlation: docs/sims/solar_hrv_correlation.md
      - Galactic Spiral Toy: docs/sims/galactic_spiral_toy.md

  - Field:
      - Overview: docs/field/index.md
      - Earth: docs/field/earth/index.md
      - Earth Data: docs/field/earth/data.md
      - Human Resonance: docs/field/human/index.md
      - Cosmic Resonance: docs/field/cosmos.md

  - Civic:
      - Overview: docs/civic/index.md
      - Conductor: docs/civic/conductor.md
      - Plazas: docs/civic/plazas.md
      - Rituals: docs/civic/rituals.md
      - Hearths: docs/civic/hearths.md
      - Governance: docs/civic/governance.md
      - Education: docs/civic/education.md
      - Economy: docs/civic/economy.md
      - Commons: docs/civic/commons.md
      - Conduits: docs/civic/conduits.md
      - Design: docs/civic/design.md
      - Loops: docs/civic/loops.md
      - Media: docs/civic/media.md

  - Cosmos:
      - Overview: docs/cosmos/index.md
      - Schumann Resonances: docs/cosmos/schumann.md
      - Solar Rhythms: docs/cosmos/solar.md
      - Lunar Tides: docs/cosmos/lunar.md
      - Galactic Spirals: docs/cosmos/galactic.md

  - Core:
      - Infinity Equation: docs/core/infinity_equation.md
