site_name: Resonant Reality
site_description: "Field, human, civic, and cosmic resonance — models, maps, and simulations"
site_author: "Terralan Mira"
repo_url: "https://github.com/TerralanMira/Resonant-reality"

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji

nav:
  - Home: index.md

  - Field Layer:
      - Overview: docs/field/index.md
      - Earth: docs/field/earth.md
      - Human: docs/field/human.md
      - Civic: docs/field/civic.md
      - Cosmos: docs/field/cosmos.md

  - Civic Layer (spiral):
      - Hearths: docs/civic/hearths.md
      - Governance: docs/civic/governance.md
      - Economy: docs/civic/economy.md
      - Education: docs/civic/education.md
      - Plazas: docs/civic/plaza.md
      - Rituals: docs/civic/rituals.md

  - Simulations:
      - Index: docs/sims/index.md
      - Spiral Resonance: docs/sims/spiral_resonance.md
      - Kuramoto Sync: docs/sims/kuramoto.md
      - LC Grid Modes: docs/sims/lc_grid.md
      - Schumann Coupling: docs/sims/schumann.md
      - Resonant Currency: docs/sims/resonant_currency.md
      - Cosmos Sims Overview: docs/cosmos/simulations.md

  - Awareness & Coherence:
      - Overview: docs/awareness/index.md
      - Practices: docs/awareness/practices.md
      - Collective Field: docs/awareness/collective.md

  - Core:
      - Infinity Equation: docs/core/infinity_equation.md
      - Atlas Model (Engine): docs/core/atlas_model.md
      - Bridge (RR ↔ Atlas): docs/bridge.md

  - Books & References:
      - Core Texts: docs/books/index.md
      - Excerpts: docs/books/excerpts.md

  - Exports:
      - Knowledge Maps: docs/exports/maps.md
      - Data Sheets: docs/exports/data.md
