site_name: Resonant Reality
site_description: >
  A living atlas of resonance across human, earth, civic, and cosmic layers —
  weaving field theory, coherence practices, and civic design into a whole.
site_url: https://your-username.github.io/Resonant-reality/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: indigo
    - scheme: slate
      primary: teal
      accent: indigo

plugins:
  - search
  - mkdocs-jupyter
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.highlight

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Books:
      - 01_Books/index.md
  - Awareness & Coherence:
      - 03_Awareness & Coherence/index.md
  - Field:
      - 04_Field Layer/index.md
      - Earth: field/earth.md
      - Human: field/human.md
      - Civic: field/civic.md
      - Cosmos: field/cosmos.md
  - Civic:
      - docs/civic/index.md
      - Conductor: docs/civic/conductor.md
      - Plazas: docs/civic/plazas.md
      - Rituals: docs/civic/rituals.md
      - Hearths: docs/civic/hearths.md
      - Governance: docs/civic/governance.md
      - Education: docs/civic/education.md
      - Economy: docs/civic/economy.md
  - Sims:
      - docs/sims/index.md
      - Resonant Currency: docs/sims/resonant_currency.md
      - The Atlas Model: docs/sims/the_atlas_model.md
      - Plaza Simulation: docs/sims/plaza.md
  - Bridge:
      - docs/bridge/index.md
  - Cosmos:
      - docs/cosmos/index.md
      - docs/cosmos/maps.md
      - docs/cosmos/simulations.md
