site_name: Resonant Whole
theme:
  name: material

nav:
  - Overview:
      - Roadmap: overview/00-roadmap.md
      - Atlas Spiral: overview/01-spiral.md
  - Glossary: glossary.md
  - TOE: toe/index.md
  - City: city/index.md
    - City: 
      - Overview: city/index.md
      - Garden: city/garden.md
      - Civic Plaza: city/plaza.md
      - Conductor: city/conductor.md
      - Hearths & Healing Loops: city/hearths.md
      - The Wild: city/wild.md
  - Earth: earth/index.md
  - Cosmos: cosmos/index.md
