site_name: Resonant Reality
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Awareness & Coherence:
      - Overview: docs/awareness/index.md
      - Anchors: docs/awareness/anchors.md
      - Practices: docs/awareness/practices.md
  - Field Layer:
      - Earth: docs/field/earth.md
      - Human: docs/field/human.md
      - Civic: docs/field/civic.md
      - Cosmos: docs/field/cosmos.md
  - Simulations:
      - Overview: docs/sims/index.md
      - Resonant Currency: docs/sims/resonant_currency.md
      - Other Models: docs/sims/other_models.md
  - Civic Applications:
      - Conductor: docs/civic/conductor.md
      - Plazas: docs/civic/plazas.md
      - Rituals: docs/civic/rituals.md
      - Hearths: docs/civic/hearths.md
      - Governance: docs/civic/governance.md
      - Education: docs/civic/education.md
      - Economy: docs/civic/economy.md
  - Bridge: docs/bridge.md
  - The Atlas Model: https://github.com/TerralanMira/The-Atlas-Model
