site_name: Resonant Whole
theme:
  name: material

nav:
  - Overview:
      - Roadmap: overview/00-roadmap.md
      - Atlas Spiral: overview/01-spiral.md
  - Glossary: glossary.md
  - TOE: toe/index.md
    - TOE:
      - Overview: toe/index.md
    - Simulations:
        - Hub: sims/index.md
        - Quickstart: sims/quickstart.md
        - Spiral Resonance: sims/spiral_resonance.md
        - Kuramoto Sync: sims/kuramoto.md
        - LC Grid Modes: sims/lc_grid.md
        - Schumann Coupling: sims/schumann.md
      - Models:
           - FPC–CFM Loop: toe/models/fpc_cfm.md 
          - Simulations: toe/models/simulations.md
    - Spiral Resonance: sims/spiral_resonance.md
  -- City:
    - Index: city/index.md
    - Garden: city/garden.md
    - Civic Plaza: city/plaza.md
    - Hearths & Healing Loops: city/hearths.md
    - The Wild: city/wild.md
    - Conductor: conductor/index.md

- Earth:
    - Index: earth/index.md
    - Planetary Layer: earth/layer.md
    - Data: earth/data.md

- Cosmos:
    - Index: cosmos/index.md
    - Stellar Layer: cosmos/layer.md
    - Ritual Calendar: cosmos/calendar.md
  - Stellar Layer: cosmos/layer.md
