site_name: Resonant Reality
site_description: Explorations of coherence, resonance, and civic-cosmic design
site_author: Terralan Mira
repo_url: https://github.com/TerralanMira/Resonant-reality
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - toc.integrate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: deep purple
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search
  - awesome-pages
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - def_list
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Civic Layer:
      - Overview: civic/index.md
      - Plazas: civic/plazas.md
      - Hearths: civic/hearths.md
      - Conductor: civic/conductor.md
      - Governance: civic/governance.md
      - Education: civic/education.md
      - Economy: civic/economy.md
      - Rituals: civic/rituals.md
  - Field Layer:
      - Overview: field/index.md
      - Human: field/human.md
      - Earth: field/earth.md
      - Cosmos: field/cosmos.md
      - Bridge: field/bridge.md
  - Awareness & Coherence:
      - index.md
  - Applications:
      - index.md
  - Simulations:
      - Overview: sims/index.md
      - Resonant Currency: sims/resonant_currency.md
      - Plaza Simulation: sims/plaza.md
      - Atlas Model: sims/atlas_model.md
  - Books:
      - index.md
