site_name: Resonant Reality
site_description: "Field, human, civic, and cosmic resonance — models, maps, and simulations"
repo_url: "https://github.com/TerralanMira/Resonant-reality"

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter
  - awesome-pages

nav:
  - Home: index.md
  - SPIRA (Keystone): spiral.md

  - Field Layer:
      - Overview: field/index.md
      - Earth: field/earth.md
      - Human: field/human.md
      - Civic: field/civic.md
      - Cosmos: field/cosmos.md

  - Civic Layer (spiral):
      - Hearths: civic/hearths.md
      - Governance: civic/governance.md
      - Economy: civic/economy.md
      - Education: civic/education.md
      - Plaza: civic/plaza.md
      - Rituals: civic/rituals.md

  - Simulations:
      - Index: sims/index.md
      - Spiral Resonance: sims/spiral_resonance.md
      - Kuramoto Sync: sims/kuramoto.md
      - LC Grid Modes: sims/lc_grid.md
      - Schumann Coupling: sims/schumann.md
      - Resonant Currency: sims/resonant_currency.md
      - Plaza (toy): sims/plaza.md
      - Orbital Resonance: sims/orbital_resonance.md

  - Bridge:
      - Atlas (Fractal Bridge): bridge/atlas.md
      - The Atlas Model (external): https://github.com/TerralanMira/The-Atlas-Model

  - Books & References:
      - Core Texts: books/index.md
      # - Excerpts: books/excerpts.md   # uncomment only if file exists

  - Exports:
      - Knowledge Maps: exports/maps.md
      - Data Sheets: exports/data.md
