blank_issues_enabled: false
contact_links:
  - name: General question / discussion
    url: https://github.com/TerralanMira/Resonant-reality/discussions
    about: Ask open questions or share insights in Discussions.
