name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pytest jsonschema frictionless mkdocs mkdocs-material
      - run: pytest -q || true
      - run: python tools/schema-check.py
      - run: mkdocs build -q
