name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # needed for gh-pages deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (from requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site (strict)
        run: mkdocs build --strict

      - name: Upload built site (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
